In [ ]:
import cv2
import keras.layers 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
import cvlib as cv


In [ ]:
def get_face(image, name):

  img= cv2.imread(image)
  print(img)
  faces, confidences = cv.detect_face(img)
  for face in faces:
        (startX,startY) = face[0],face[1]
        (endX,endY) = face[2],face[3]
        cropped_image = img[startY:endY, startX:endX]
        cv2.imwrite(outputPath + name, cropped_image)
        return cropped_image


In [ ]:
def resize_picture(in_file, out_file, width_out, height_out):
    img = in_file
    resize = tf.keras.layers.Resizing (width_out, height_out, interpolation='bilinear', crop_to_aspect_ratio=False)
    resized_image = resize(img)
    image_array = tf.keras.utils.img_to_array(resized_image)
    cv2.imwrite(resize_path + out_file,image_array)

In [ ]:
import os
import glob

def clean_folder(folderPath):
    files = glob.glob(folderPath + '*')
    for f in files:
        os.remove(f)

In [ ]:
path = 'C:/Users/prokopj/team_prep/'
outputPath = 'C:/Users/prokopj/team_cropped/'
resize_path ='C:/Users/prokopj/team/'

In [ ]:
def go_through_dataset_crop(n):
  clean_folder(outputPath)
  data_pict = pd.read_csv('C:/Users/prokopj/pairsteam.csv')
  sample = data_pict.sample(n)
  picts = []
  for x in range(0, (n)):
    print(str(sample.iloc[x, 0]))
    image = str(sample.iloc[x, 0])
    get_face(path + image, image)
        


In [ ]:
def go_through_dataset_resize(n, size):
  clean_folder(outputPath)
  clean_folder(resize_path)
  data_pict = pd.read_csv('C:/Users/prokopj/pairsteam.csv')
  sample = data_pict.sample(n)
  picts = []
  for row in range(len(sample)):
    pict = sample.iloc[row, 0]
    picts.append(pict)
  for i in range(len(picts)):
      x =  path + str(picts[i])
      image = get_face(x, picts[i])
      if image is not None:
            resize_picture(image,picts[i], size, size)

In [ ]:
go_through_dataset_resize(10, 224)

[[[ 20   8   8]
  [ 19   7   7]
  [ 20   8   6]
  ...
  [154 163 160]
  [152 163 160]
  [149 160 157]]

 [[ 21   9   9]
  [ 20   8   8]
  [ 21   9   7]
  ...
  [151 160 157]
  [149 160 157]
  [149 160 157]]

 [[ 20   8   6]
  [ 19   7   5]
  [ 20   8   6]
  ...
  [148 157 154]
  [146 157 154]
  [148 159 156]]

 ...

 [[126  81   7]
  [126  81   7]
  [126  81   7]
  ...
  [124 101   1]
  [123 103   2]
  [125 105   4]]

 [[125  80   6]
  [126  81   7]
  [126  81   7]
  ...
  [125 105   4]
  [123 103   2]
  [122 102   1]]

 [[126  81   7]
  [127  82   8]
  [127  82   8]
  ...
  [123 103   2]
  [123 103   2]
  [124 104   3]]]
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[ 21  15  16]
  [ 19  13  14]
  [ 21  15  16]
  ..